# Generated by Django 5.2.9 on 2025-12-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
